# -*- coding: utf-8 -*-
"""Task-4_Text-Generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15g4FJe496T0XksWO2XIYWJf3VaCwgREp

# **TASK -4 GENERATIVE TEXT MODEL BY SAKSHI SRIVASTAVA**
**CREATE A TEXT GENERATION MODEL USING GPT OR LSTM TO GENERATE COHERENT PARAGRAPHS ON SPECIFIC TOPICS.**
"""

# Model: GPT-2 from Hugging Face Transformers

from transformers import pipeline, set_seed

def generate_text(prompt):
    # Load the text-generation pipeline with GPT-2
    generator = pipeline("text-generation", model="gpt2")

    # Set random seed for reproducibility
    set_seed(42)

    # Generate text with max length of 100 tokens
    result = generator(prompt, max_length=100, num_return_sequences=1)

    # Return the generated paragraph
    return result[0]['generated_text']

# Main block to run text generation
if __name__ == "__main__":
    # Example topic prompt
    prompt = "Artificial intelligence is transforming the future by"

    # Generate and print the paragraph
    print("Generated Text:\n")
    print(generate_text(prompt))

