# -*- coding: utf-8 -*-
"""Task_1_Text_Summarization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lW0LF2bM-vTH6q77mQHvwHASGjZF4kU0

# **CODTECH INTERNSHIP - by SAKSHI SIVASTAVA**

# **TASK 1 TEXT SUMMARIZATION TOOL**

**CREATE A TOOL THAT SUMMARIZES LENGTHY ARTICLES USING NATURAL LANGUAGE PROCESSING TECHNIQUES.**
"""

# Install Hugging Face Transformers
!pip install transformers

# Install the required library
from transformers import pipeline

"""**MODEL USED <CODE> facebook/bart-large-cnn </CODE>**"""

# Define a function to summarize text using a pre-trained model
def summarize_text(text):
    # Load BART model for summarization
    summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

    # Generate the summary with specific length constraints
    summary = summarizer(text, max_length=130, min_length=30, do_sample=False)

    return summary[0]['summary_text']

# Example long text to summarize
article = """
Artificial Intelligence (AI) is revolutionizing every aspect of our lives — from virtual assistants and recommendation systems
to self-driving cars and smart diagnostics in healthcare. As the technology advances, it raises questions about ethics,
regulation, and its long-term impact on employment and society at large.Artificial Intelligence (AI) is a broad field of computer science focused on creating machines capable of performing tasks that typically require human intelligence.
This includes learning, reasoning, problem-solving, and making decisions. AI systems utilize techniques like machine learning and deep learning to process data, identify patterns,
and make predictions without being explicitly programmed for every scenario. The field is rapidly evolving, with applications ranging
from voice assistants and recommendation systems to medical diagnosis and self-driving cars
"""

# Generate and print the summary
result = summarize_text(article)
print("Summary:\n", result)

"""**MODEL USED <CODE> sshleifer/distilbart-cnn-12-6 </CODE>**"""

def summarize_text(text):
    summarizer = pipeline("summarization",model="sshleifer/distilbart-cnn-12-6")
    #summarizer = pipeline("summarization")
    summary = summarizer(text, max_length=60, min_length=30, do_sample=False)
    return summary[0]['summary_text']

if __name__ == "__main__":
    article ="""Artificial Intelligence (AI) is a broad field of computer science focused
    on creating machines capable of performing tasks that typically require human intelligence.
    This includes learning, reasoning, problem-solving, and making decisions.
    AI systems utilize techniques like machine learning and deep learning to process data, identify patterns,
    and make predictions without being explicitly programmed for every scenario. The field is rapidly evolving, with applications ranging
    from voice assistants and recommendation systems to medical diagnosis and self-driving cars."""
    result = summarize_text(article)
    print("\nSummary:\n", result)

